[project]
name = "core"
version = "0.1.0"
description = "Core SST resources"
requires-python = "==3.12.*"
dependencies = ["requests>=2.32.3"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
